name: Build Jewish Magic Dictionary

on:
  push:
    paths:
      - "The Encyclopedia of Jewish Myth, Magic and Mysticism - 2nd Edition (2016).txt"
      - "scripts/extract_dictionary.py"
  workflow_dispatch:

# 👇 This makes sure the bot can push commits back to the repo
permissions:
  contents: write

jobs:
  build-dictionary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run extraction script
        run: python scripts/extract_dictionary.py

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add jewish_magic_dictionary.json
          git commit -m "Auto-generate jewish_magic_dictionary.json" || echo "No changes to commit"
          git push
